import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { renderRemoteWebApp } from "../src/remote-web.js";

test("remote web app renders an English mobile-first control shell", () => {
  const html = renderRemoteWebApp();

  assert.match(html, /<html lang="en">/u);
  assert.match(html, /<title>Dream Code<\/title>/u);
  assert.match(html, /rel="manifest"/u);
  assert.match(html, /\/manifest\.webmanifest\?v=4/u);
  assert.match(html, /theme-color/u);
  assert.match(html, /apple-mobile-web-app-capable/u);
  assert.match(html, /apple-touch-icon/u);
  assert.match(html, /\/favicon\.ico\?v=4/u);
  assert.match(html, /\/icon-192\.png\?v=4/u);
  assert.match(html, /\/icon-512\.png\?v=4/u);
  assert.match(html, /msapplication-TileImage/u);
  assert.match(html, /og:image/u);
  assert.match(html, /Dream Code Remote/u);
  assert.match(html, /Projects/u);
  assert.match(html, /Recent Threads/u);
  assert.match(html, /Threads/u);
  assert.match(html, /New Thread/u);
  assert.match(html, /Checking connection/u);
  assert.match(html, /Paired/u);
  assert.match(html, /Install App/u);
  assert.match(html, /Install Dream Code/u);
  assert.match(html, /Add to Home screen/u);
  assert.match(html, /display-mode: standalone/u);
  assert.match(html, /beforeinstallprompt/u);
  assert.match(html, /Logout/u);
  assert.match(html, /Logout from this device\?/u);
  assert.match(html, /Pair this device/u);
  assert.match(html, /Thread/u);
  assert.match(html, /Stop/u);
  assert.match(html, /Working/u);
  assert.match(html, /Prompt received/u);
  assert.match(html, /Cancelled/u);
  assert.match(html, /\/api\/commands\/.*\/cancel/u);
  assert.match(html, /Delete/u);
  assert.match(html, /Delete session\?/u);
  assert.match(html, /Rename thread/u);
  assert.match(html, /Thread actions/u);
  assert.match(html, /Save name/u);
  assert.match(html, /PATCH/u);
  assert.match(html, /This cannot be undone/u);
  assert.match(html, /modal-layer/u);
  assert.match(html, /confirm-dialog/u);
  assert.match(html, /Deleting\.\.\./u);
  assert.match(html, /\/api\/sessions\/.*DELETE/u);
  assert.match(html, /\/api\/sessions\/.*encodeURIComponent/u);
  assert.match(html, /\/api\/me/u);
  assert.match(html, /Send a prompt to start coding remotely/u);
  assert.match(html, /<div id="app"><\/div>/u);
  assert.match(html, /dream\.remote\.token/u);
  assert.match(html, /\/api\/events\?token=/u);
  assert.match(html, /visibilitychange/u);
  assert.match(html, /setInterval/u);
  assert.match(html, /\/api\/projects/u);
  assert.match(html, /serviceWorker\.register/u);
  assert.match(html, /Notification\.requestPermission/u);
  assert.match(html, /showNotification/u);
  assert.match(html, /dream-notification-click/u);
  assert.match(html, /new URLSearchParams/u);
  assert.match(html, /serviceWorker\?\.addEventListener/u);
  assert.doesNotMatch(html, /\/api\/uploads/u);
  assert.match(html, /dataBase64/u);
  assert.match(html, /attachment-tray/u);
  assert.match(html, /attach-button/u);
  assert.match(html, /command-menu/u);
  assert.match(html, /Slash commands/u);
  assert.match(html, /\/swarm/u);
  assert.match(html, /Uploading\.\.\./u);
  assert.doesNotMatch(html, /Recent Runs/u);
  assert.match(html, /min-width: 0/u);
  assert.match(html, /grid-template-columns: 52px minmax\(0, 1fr\) 52px/u);
  assert.match(html, /width: 0/u);
  assert.match(html, /left: 0/u);
  assert.match(html, /right: 26px/u);
  assert.match(html, /@media \(max-width: 340px\)/u);
  assert.match(html, /@media \(min-width: 700px\)/u);
  assert.match(html, /@media \(min-width: 1024px\)/u);
  assert.doesNotMatch(html, /max-width: 860px/u);
  assert.doesNotMatch(html, /max-width: 1040px/u);
  assert.match(html, /thinking-bars/u);
  assert.match(html, /activity-pulse/u);
  assert.match(html, /activity-ellipsis/u);
  assert.match(html, /live-output/u);
  assert.match(html, /Live output/u);
  assert.match(html, /swarm-frame/u);
  assert.match(html, /swarm-running/u);
  assert.match(html, /markdown-result/u);
  assert.match(html, /md-inline-code/u);
  assert.match(html, /md-link/u);
  assert.match(html, /md-divider/u);
  assert.match(html, /activity-list/u);
  assert.match(html, /history\.pushState/u);
  assert.match(html, /popstate/u);
  assert.match(html, /scrollIntoView/u);
  assert.match(html, /requestAnimationFrame/u);
  assert.match(html, /thread-scroll-anchor/u);
  assert.match(html, /--composer-clearance/u);
  assert.match(html, /height: calc\(var\(--composer-clearance\) \+ env\(safe-area-inset-bottom\)\)/u);
  assert.match(html, /focus-within/u);
  assert.match(html, /row-sub/u);
  assert.match(html, /recentThreads/u);
  assert.match(html, /top-spacer/u);
  assert.match(html, /page-transition/u);
  assert.match(html, /page-forward/u);
  assert.match(html, /page-back/u);
  assert.match(html, /page-replace/u);
  assert.match(html, /page-forward-enter/u);
  assert.match(html, /page-back-enter/u);
  assert.match(html, /prefers-reduced-motion/u);
  assert.doesNotMatch(html, /window\.confirm/u);
  assert.doesNotMatch(html, /터미널/u);
});

test("remote web navigation does not cancel running commands on back navigation", async () => {
  const app = await readFile("src/remote-web-app.tsx", "utf8");
  const shell = await readFile("src/remote-web-shell.tsx", "utf8");
  const navigation = await readFile("src/remote-web-navigation.ts", "utf8");
  const thread = await readFile("src/remote-web-thread.tsx", "utf8");
  const composer = await readFile("src/remote-web-composer.tsx", "utf8");
  const ops = await readFile("src/remote-web-session-ops.ts", "utf8");
  const notificationNavigation = await readFile("src/remote-web-notification-navigation.ts", "utf8");
  const data = await readFile("src/remote-web-data.ts", "utf8");

  assert.doesNotMatch(app, /cancelCommands/u);
  assert.doesNotMatch(navigation, /onLeaveThread/u);
  assert.match(navigation, /NavigationDirection/u);
  assert.match(navigation, /historyStateWithIndex/u);
  assert.match(navigation, /setDirection\("forward"\)/u);
  assert.match(navigation, /setDirection\(nextIndex < indexRef\.current \? "back" : "forward"\)/u);
  assert.match(ops, /\/api\/commands\/.*\/cancel/u);
  assert.match(ops, /retryCommand/u);
  assert.match(ops, /\/api\/commands/u);
  assert.match(ops, /openSessionById/u);
  assert.match(notificationNavigation, /dream-notification-click/u);
  assert.match(notificationNavigation, /scrollTargetSessionId/u);
  assert.match(app, /renderAuthScreen/u);
  assert.match(app, /renameRemoteSession/u);
  assert.match(shell, /projectForSession/u);
  assert.match(shell, /onRetry/u);
  assert.match(thread, /MarkdownView markdown=\{props\.turn\.content\}/u);
  assert.match(thread, /LiveOutput/u);
  assert.match(thread, /latestSwarmFrame/u);
  assert.match(thread, /stripAnsi/u);
  assert.match(composer, /remoteSlashCommands/u);
  assert.match(composer, /requestRemoteNotificationPermission/u);
  assert.match(composer, /pendingUploadPayloads/u);
  assert.match(data, /useRemoteWorkspaceRefresh/u);
  assert.match(data, /window\.addEventListener\("focus"/u);
  assert.match(data, /document\.addEventListener\("visibilitychange"/u);
  assert.match(data, /window\.setInterval\(refresh, 10_000\)/u);
  assert.match(data, /requestJson<\{ readonly projects/u);
  assert.doesNotMatch(composer, /slice\(0, 8\)/u);
});

test("remote web shows command progress as mobile process cards", async () => {
  const thread = await readFile("src/remote-web-thread.tsx", "utf8");
  const commandSummary = await readFile("src/remote-web-command-summary.tsx", "utf8");
  const activity = await readFile("src/remote-web-activity.tsx", "utf8");
  const css = await readFile("src/remote-web.css", "utf8");

  assert.match(thread, /process-card/u);
  assert.match(thread, /ProcessSummary/u);
  assert.match(thread, /PersistentProcessTimeline/u);
  assert.match(thread, /FinalCommandResult/u);
  assert.match(thread, /CommandOutcomeSummary/u);
  assert.match(thread, /final-result/u);
  assert.match(commandSummary, /CommandFreshness/u);
  assert.match(commandSummary, /retry-command/u);
  assert.match(commandSummary, /command-outcome/u);
  assert.match(commandSummary, /stale-command/u);
  assert.match(thread, /ActivityTimeline command=\{command\}/u);
  assert.match(activity, /latestActivity/u);
  assert.match(activity, /step-meter/u);
  assert.match(activity, /activity-kind/u);
  assert.match(activity, /process-insights/u);
  assert.match(css, /\.process-card/u);
  assert.match(css, /\.process-summary/u);
  assert.match(css, /\.final-result/u);
  assert.match(css, /\.command-outcome/u);
  assert.match(css, /\.retry-command/u);
  assert.match(css, /\.stale-command/u);
  assert.match(css, /\.activity-kind\.tool/u);
  assert.match(css, /\.activity-kind\.verify/u);
  assert.match(css, /grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/u);
});

test("remote web slash menu hides interactive-only commands", async () => {
  const remoteSlash = await readFile("src/remote-slash-commands.ts", "utf8");

  assert.match(remoteSlash, /remoteSlashCommandNames/u);
  assert.match(remoteSlash, /"\/swarm"/u);
  assert.match(remoteSlash, /"\/workflow"/u);
  assert.doesNotMatch(remoteSlash, /"\/agents"/u);
  assert.doesNotMatch(remoteSlash, /"\/login"/u);
  assert.doesNotMatch(remoteSlash, /"\/model"/u);
  assert.match(remoteSlash, /!slashCommands\.some/u);
});
